
language: node_js
node_js: 
 - "stable"

branches:
    only:
     - dev
     - /feature/
before_script:
 - npm install -g firebase-tools
script:
 - npm run build
 
after_script:
 - firebase deploy --token $FIREBASE_TOKEN

 after_success:
 - echo "Firebase deploy succesfull!"
 
notifications:
    email:
        on_failure: change
        on_success: change