language: node_js
node_js: 
 - "11.12.0"

branches:
    only:
     - dev
     - /feature-.*/
before_script:
 - npm install -g firebase-tools
 - npm install -g vue/cli
 
script:
 - npm run build
 
after_success:
 - firebase deploy --token $FIREBASE_TOKEN
 
notifications:
    email:
        on_failure: change
        on_success: change